### ISSUE TITLE
Unable to change the running user

### ISSUE THREAD

**Issue by mrvaghani** [The-Kube-Way/nsd#1]
No matter how I set the environment variable UID and GID, the container starts as 991 and then fails because it's unable to chown the mounted volumes. Is there anything you would recommend I test on my side to verify if this is a user error or not? 

Steps to recreate:

1. Create docker-compose.yml

```bash
version: '3.7'

services:
  nsd:
    container_name: nsd
    restart: always
    image: ghcr.io/the-kube-way/nsd:test
    read_only: true
    tmpfs:
      - /tmp
      - /var/db/nsd
    volumes:
      - /opt/nsd/conf:/etc/nsd:ro
      - /opt/nsd/zones:/zones
      - /opt/nsd/keys:/keys:ro
    ports:
      - "8554:53"
      - "8554:53/udp"
```

2. Set environment variables

```bash
export UID=${UID}
export GID=${GID}
```

3. Start the container

```bash
docker-compose up
```

The error I am getting:

```bash
user@localhost:/opt/nsd$ docker logs -f nsd
+ UID=991
+ GID=991
+ chown -R 991:991 /var/db/nsd /tmp
chown: /var/db/nsd: Operation not permitted
chown: /var/db/nsd: Operation not permitted
chown: /tmp: Operation not permitted
chown: /tmp: Operation not permitted
```

System information:

OS: Ubuntu 20.04.3 LTS
Docker version 20.10.11, build dea9396
docker-compose version 1.29.2, build 5becea4c

Please let me know if you are able to recreate this.

**Comment by fl42** [comment]
Hello,

You should set environment variables to the container using `environment` key in your docker compose file (see [docs](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers))

**Comment by mrvaghani** [comment]
Thanks! Adding that solved my problem.

```bash
environment:
      - UID=1000
      - GID=1000
```
